import { useEffect, useState } from 'react'; import { categoriesApi } from '../services/api'; import { useTranslation } from '../i18n'; import { Plus, Edit2, Trash2 } from 'lucide-react'; import toast from 'react-hot-toast';

export default function Categories() {
  const { t } = useTranslation();
  const [categories, setCategories] = useState<any[]>([]); const [modal, setModal] = useState<any>(null);
  useEffect(() => { categoriesApi.getAll().then(r=>setCategories(r.data.data||[])); }, []);
  const handleDelete = async (id: string) => { if(!confirm(t('categories__confirmDelete'))) return; await categoriesApi.delete(id); setCategories(p=>p.filter(x=>x.id!==id)); toast.success(t('categories__deleted')); };

  return (
    <div><div className="flex justify-between items-center mb-6"><h1 className="text-xl font-semibold text-base-900 dark:text-white tracking-tight">{t('categories__title')}</h1><button onClick={()=>setModal({})} className="flex items-center gap-1.5 bg-base-900 dark:bg-white text-white dark:text-base-900 px-4 py-2 rounded-lg font-medium text-sm hover:bg-base-700 dark:hover:bg-base-200 transition-colors"><Plus size={16}/> {t('categories__new')}</button></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{categories.map(c=>(<div key={c.id} className="bg-white dark:bg-base-950 rounded-xl p-5 border border-base-200 dark:border-base-800 hover:border-base-300 dark:hover:border-base-700 transition-colors"><div className="flex justify-between items-start"><h3 className="font-medium text-base-900 dark:text-white">{c.name}</h3><div className="flex gap-1"><button onClick={()=>setModal(c)} className="p-1 text-base-400 hover:text-base-900 dark:hover:text-white"><Edit2 size={14}/></button><button onClick={()=>handleDelete(c.id)} className="p-1 text-base-400 hover:text-red-500"><Trash2 size={14}/></button></div></div><p className="text-xs text-base-400 mt-1">{c.description||t('categories__noDesc')}</p><div className="flex items-center gap-2 mt-4"><span className="text-lg font-semibold text-base-900 dark:text-white">{c.productCount}</span><span className="text-xs text-base-400">{t('categories__products')}</span>{c.gender&&<span className="ml-auto text-[10px] bg-base-100 dark:bg-base-900 text-base-500 px-2 py-0.5 rounded-full">{c.gender}</span>}</div></div>))}</div>
      {modal && <CatModal t={t} cat={modal} onClose={()=>setModal(null)} onSave={(c:any)=>{if(c.id) setCategories(p=>p.map(x=>x.id===c.id?c:x)); else setCategories(p=>[...p,c]); setModal(null);}}/>}
    </div>
  );
}

function CatModal({ t, cat, onClose, onSave }: any) {
  const [form, setForm] = useState({ name: cat.name || '', description: cat.description || '', gender: cat.gender || '' }); const [loading, setLoading] = useState(false);
  const cls = "w-full border border-base-200 dark:border-base-800 rounded-lg px-4 py-3 text-sm outline-none bg-white dark:bg-base-950 text-base-900 dark:text-white focus:border-base-400 transition-colors";
  const h = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); try { const r = cat.id ? await categoriesApi.update(cat.id, form) : await categoriesApi.create(form); onSave(r.data.data); toast.success(cat.id?t('categories__updated'):t('categories__created')); } catch(err:any){ toast.error(err.response?.data?.error?.message||t('categories__error')); } setLoading(false); };
  return (<div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50" onClick={onClose}><div className="bg-white dark:bg-base-950 rounded-xl p-6 w-full max-w-md border border-base-200 dark:border-base-800 shadow-xl" onClick={e=>e.stopPropagation()}><h2 className="text-lg font-semibold text-base-900 dark:text-white mb-5">{cat.id?t('categories__modal_edit'):t('categories__modal_new')}</h2><form onSubmit={h} className="space-y-3"><input className={cls} placeholder={t('categories__field_name')} required value={form.name} onChange={e=>setForm(s=>({...s,name:e.target.value}))}/><textarea className={cls} placeholder={t('categories__field_desc')} rows={3} value={form.description} onChange={e=>setForm(s=>({...s,description:e.target.value}))}/><select className={cls} value={form.gender} onChange={e=>setForm(s=>({...s,gender:e.target.value}))}><option value="">{t('categories__gender_none')}</option><option value="Men">{t('categories__gender_men')}</option><option value="Women">{t('categories__gender_women')}</option><option value="Unisex">{t('categories__gender_unisex')}</option><option value="Kids">{t('categories__gender_kids')}</option></select><div className="flex gap-3 pt-2"><button type="button" onClick={onClose} className="flex-1 py-2.5 border border-base-200 dark:border-base-800 rounded-lg font-medium text-base-600 dark:text-base-400 hover:bg-base-50 dark:hover:bg-base-900 transition-colors">{t('cancel')}</button><button type="submit" disabled={loading} className="flex-1 py-2.5 bg-base-900 dark:bg-white text-white dark:text-base-900 rounded-lg font-medium hover:bg-base-700 dark:hover:bg-base-200 disabled:opacity-50 transition-colors">{loading?'...':t('save')}</button></div></form></div></div>);
}
