import { useEffect, useState } from 'react'; import { ordersApi } from '../services/api'; import { CheckCircle, Truck, XCircle, Package, Clock } from 'lucide-react'; import toast from 'react-hot-toast';

const si: Record<string, any> = { Pending: Clock, Confirmed: CheckCircle, Shipped: Truck, Delivered: Package, Cancelled: XCircle };
const sf: Record<string, string[]> = { Pending: ['Confirmed','Cancelled'], Confirmed: ['Shipped','Cancelled'], Shipped: ['Delivered'] };
const sc: Record<string, string> = { Pending: 'bg-amber-100 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400', Delivered: 'bg-green-100 dark:bg-green-900/30', Cancelled: 'bg-red-100 dark:bg-red-900/30' };

export default function Orders() {
  const [orders, setOrders] = useState<any[]>([]); const [expanded, setExpanded] = useState<string|null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { ordersApi.getAll({pageSize:200}).then(r=>setOrders(r.data.data?.items||[])).finally(()=>setLoading(false)); }, []);
  const updateStatus = async (id: string, status: string) => { try{await ordersApi.updateStatus(id,{status});setOrders(p=>p.map(o=>o.id===id?{...o,status}:o));toast.success('Actualizado');}catch(err:any){toast.error(err.response?.data?.error?.message||'Error');} };
  const cancel = async (id: string) => { if(!confirm('¿Cancelar?')) return; try{await ordersApi.cancel(id);setOrders(p=>p.map(o=>o.id===id?{...o,status:'Cancelled'}:o));toast.success('Cancelado');}catch(err:any){toast.error(err.response?.data?.error?.message||'Error');} };

  return (<div><h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-8">Pedidos ({orders.length})</h1>
    {loading?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-20 bg-gray-100 dark:bg-gray-800 rounded-xl animate-pulse"/>)}</div>:
    <div className="space-y-3">{orders.map(o=>{const I=si[o.status]||Package;const ns=sf[o.status]||[];
      return (<div key={o.id} className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm"><div className="p-5 flex items-center justify-between cursor-pointer" onClick={()=>setExpanded(expanded===o.id?null:o.id)}><div className="flex items-center gap-4"><div className={`w-10 h-10 rounded-xl flex items-center justify-center ${sc[o.status]||'bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400'}`}><I size={18}/></div><div><p className="font-mono text-sm text-gray-500">{o.orderNumber}</p><p className="font-medium text-gray-900 dark:text-white">{o.customerName}</p></div></div><div className="flex items-center gap-3"><span className={`px-3 py-1 rounded-full text-xs font-semibold ${o.status==='Pending'?'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400':o.status==='Delivered'?'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400':'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400'}`}>{o.status}</span><span className="font-bold text-indigo-600 dark:text-indigo-400">${o.total.toFixed(2)}</span></div></div>
        {expanded===o.id&&(<div className="px-5 pb-5 border-t dark:border-gray-700 pt-4"><div className="grid md:grid-cols-3 gap-4 mb-4 text-sm"><div><p className="text-gray-400">Envío a</p><p className="font-medium text-gray-900 dark:text-white">{o.shippingAddress||'-'}</p></div><div><p className="text-gray-400">Notas</p><p className="text-gray-900 dark:text-white">{o.notes||'-'}</p></div><div><p className="text-gray-400">Fecha</p><p className="text-gray-900 dark:text-white">{new Date(o.createdAt).toLocaleString()}</p></div></div><div className="space-y-2 mb-4">{o.items?.map((i:any)=>(<div key={i.id} className="flex justify-between text-sm py-1 border-b border-gray-50 dark:border-gray-800 text-gray-700 dark:text-gray-300"><span>{i.productName} x{i.quantity} ({i.size})</span><span className="font-medium">${i.total.toFixed(2)}</span></div>))}</div><div className="flex justify-end gap-2 text-sm text-gray-700 dark:text-gray-300"><span>Sub: ${o.subtotal.toFixed(2)}</span><span>IVA: ${o.tax.toFixed(2)}</span><span>Envío: ${o.shippingCost.toFixed(2)}</span><span className="font-bold text-lg text-gray-900 dark:text-white">Total: ${o.total.toFixed(2)}</span></div>
          {ns.length>0&&<div className="flex gap-2 mt-4 pt-4 border-t dark:border-gray-700">{ns.map(s=><button key={s} onClick={()=>s==='Cancelled'?cancel(o.id):updateStatus(o.id,s)} className={`px-4 py-2 rounded-xl text-sm font-semibold ${s==='Cancelled'?'bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 hover:bg-red-100 dark:hover:bg-red-900/40':'bg-indigo-50 dark:bg-indigo-900/20 text-indigo-600 dark:text-indigo-400 hover:bg-indigo-100 dark:hover:bg-indigo-900/40'}`}>{s==='Cancelled'?'Cancelar':s==='Confirmed'?'Confirmar':s==='Shipped'?'Enviar':s}</button>)}</div>}
        </div>)}
      </div>)})}</div>}
  </div>);
}
