import { useEffect, useState } from 'react'; import { ordersApi } from '../services/api'; import { useTranslation } from '../i18n'; import { CheckCircle, Truck, XCircle, Package, Clock } from 'lucide-react'; import toast from 'react-hot-toast';

const si: Record<string, any> = { Pending: Clock, Confirmed: CheckCircle, Shipped: Truck, Delivered: Package, Cancelled: XCircle };
const sf: Record<string, string[]> = { Pending: ['Confirmed','Cancelled'], Confirmed: ['Shipped','Cancelled'], Shipped: ['Delivered'] };

const actionLabels: Record<string, string> = { Cancelled:'orders__cancel', Confirmed:'orders__confirm', Shipped:'orders__ship' };

export default function Orders() {
  const { t } = useTranslation();
  const [orders, setOrders] = useState<any[]>([]); const [expanded, setExpanded] = useState<string|null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { ordersApi.getAll({pageSize:200}).then(r=>setOrders(r.data.data?.items||[])).finally(()=>setLoading(false)); }, []);
  const updateStatus = async (id: string, status: string) => { try{await ordersApi.updateStatus(id,{status});setOrders(p=>p.map(o=>o.id===id?{...o,status}:o));toast.success(t('orders__updated'));}catch(err:any){toast.error(err.response?.data?.error?.message||t('orders__error'));} };
  const cancel = async (id: string) => { if(!confirm(t('orders__cancelConfirm'))) return; try{await ordersApi.cancel(id);setOrders(p=>p.map(o=>o.id===id?{...o,status:'Cancelled'}:o));toast.success(t('orders__cancelled'));}catch(err:any){toast.error(err.response?.data?.error?.message||t('orders__error'));} };

  return (<div><h1 className="text-xl font-semibold text-base-900 dark:text-white mb-6 tracking-tight">{t('orders')} <span className="text-base-400 font-normal">({orders.length})</span></h1>
    {loading?<div className="space-y-2">{[1,2,3].map(i=><div key={i} className="h-16 bg-base-100 dark:bg-base-900 rounded-lg animate-pulse"/>)}</div>:
    <div className="space-y-2">{orders.map(o=>{const I=si[o.status]||Package;const ns=sf[o.status]||[];
      return (<div key={o.id} className="bg-white dark:bg-base-950 rounded-xl border border-base-200 dark:border-base-800 hover:border-base-300 dark:hover:border-base-700 transition-colors"><div className="p-4 flex items-center justify-between cursor-pointer" onClick={()=>setExpanded(expanded===o.id?null:o.id)}><div className="flex items-center gap-3"><div className={`w-9 h-9 rounded-lg flex items-center justify-center bg-base-100 dark:bg-base-900 text-base-600 dark:text-base-400`}><I size={16}/></div><div><p className="font-mono text-[11px] text-base-400">{o.orderNumber}</p><p className="text-sm font-medium text-base-900 dark:text-white">{o.customerName}</p></div></div><div className="flex items-center gap-3"><span className={`px-2 py-0.5 rounded text-[11px] font-medium uppercase tracking-wide ${o.status==='Pending'?'bg-base-100 text-base-600 dark:bg-base-900 dark:text-base-400':o.status==='Delivered'?'bg-base-100 text-base-600 dark:bg-base-900 dark:text-base-400':'bg-base-100 text-base-600 dark:bg-base-900 dark:text-base-400'}`}>{o.status}</span><span className="font-semibold text-base-900 dark:text-white text-sm">${o.total.toFixed(2)}</span></div></div>
        {expanded===o.id&&(<div className="px-4 pb-4 border-t border-base-100 dark:border-base-900 pt-3"><div className="grid md:grid-cols-3 gap-4 mb-3 text-xs"><div><p className="text-base-400 mb-0.5">{t('orders__shippingTo')}</p><p className="font-medium text-base-900 dark:text-white">{o.shippingAddress||'-'}</p></div><div><p className="text-base-400 mb-0.5">{t('orders__notes')}</p><p className="text-base-900 dark:text-white">{o.notes||'-'}</p></div><div><p className="text-base-400 mb-0.5">{t('orders__date')}</p><p className="text-base-900 dark:text-white">{new Date(o.createdAt).toLocaleString()}</p></div></div><div className="space-y-1.5 mb-3">{o.items?.map((i:any)=>(<div key={i.id} className="flex justify-between text-xs py-1 border-b border-base-50 dark:border-base-900 text-base-600 dark:text-base-400"><span>{i.productName} x{i.quantity} ({i.size})</span><span className="font-medium">${i.total.toFixed(2)}</span></div>))}</div><div className="flex justify-end gap-3 text-xs text-base-500"><span>Sub: ${o.subtotal.toFixed(2)}</span><span>IVA: ${o.tax.toFixed(2)}</span><span>Envío: ${o.shippingCost.toFixed(2)}</span><span className="font-semibold text-sm text-base-900 dark:text-white">Total: ${o.total.toFixed(2)}</span></div>
          {ns.length>0&&<div className="flex gap-2 mt-3 pt-3 border-t border-base-100 dark:border-base-900">{ns.map(s=><button key={s} onClick={()=>s==='Cancelled'?cancel(o.id):updateStatus(o.id,s)} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${s==='Cancelled'?'bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 hover:bg-red-100 dark:hover:bg-red-900/40':'bg-base-100 dark:bg-base-900 text-base-700 dark:text-base-300 hover:bg-base-200 dark:hover:bg-base-800'}`}>{t(actionLabels[s]||s)}</button>)}</div>}
        </div>)}
      </div>)})}</div>}
  </div>);
}
